### ISSUE TITLE
Cannot provide custom `tensordot` method

### ISSUE THREAD

**Issue by srush** [dgasmith/opt_einsum#101]
As far as I can tell there is no way to provide a custom `tensordot` method. I tried pretty hard, but the code path seems to fail on examples like `contract("abc,ab-> ac")`.

**Comment by jcmgray** [comment]
Maybe you could expand a bit on what you have tried? The equation you give as an example cannot be framed as a simple [tensordot](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.tensordot.html), since the index ``'a'`` appears 3 times.

**Comment by jcmgray** [comment]
The main role of ``opt_einsum`` I would consider is to find and perform pairwise contraction orderings.

With regard to point 1, does your backend provide an ``einsum`` function? If it doesn't then this isn't a bug, its just that certain pairwise contractions such as the one you give cannot be done with ``tensordot`` alone. I think the [docs](https://optimized-einsum.readthedocs.io/en/stable/backends.html) are reasonably clear on when an ``einsum`` implementation is required:

> For a contraction to be possible without using a backend einsum, it must satisfy the following rule: in the full expression (including output indices) each index must appear twice. In other words, each dimension must be contracted with one other dimension, or left alone.

There are simple cases (such as here where ``'a'`` is just a broadcast dimension) where one could imagine manually implementing things, but ``einsum`` has such myriad syntax uses that it gets v complex to handle, let alone performance considerations.

**Comment by jcmgray** [comment]
@dgasmith I think the issue is just the type of contraction requiring a non-existent ``einsum``.

> I see, I guess I got tripped up by this statement: "In fact, any library that provides a tensordot() and transpose() implementation can perform most normal contractions." Keeping axes around felt pretty normal to me (for instance any sort of batching).

Yes I guess 'normal' is pretty subjective! I was coming from the background of physics and einstein notation when I wrote that I suspect.

> Any idea for the true minimal set of functions a backend could implement such that opt-einsum could be used as a front-end?

I think ``einsum`` can do things no other function can, but some extras that come to mind are:
* ``diag`` (``ii->i``)
* ``trace`` (``ii->``)
* ``multiply`` (``i,i->i``)
* ``sum`` (``i->``)

But once they start getting mixed together, e.g. (``iij->i``) it all gets a bit more complicated and complete support seems pretty impossible. Trying to support specific, common cases such as batch dimensions would probably be the way to proceed (might actually be possible with #95), but even then, there is not standard 'vectorize' function in the same way that ``tensordot`` is 'standard', so one would have to use python looping and ``concat`` or something.

**Comment by dgasmith** [comment]
I would lean with @jcmgray that this functionality could be complex to implement. At the moment, you can hack this with the following:
```python
import opt_einsum as oe
oe.backends.dispatch._cached_funcs["tensordor", "numpy"] = custom_func
```

Happy to take a PR which is well documented with edge cases.
