### ISSUE TITLE
Contracting a tensor with selection rules

### ISSUE THREAD

**Issue by nquesada** [dgasmith/opt_einsum#121]
Imagine that you have a tensor ```T_{ijkl} (0<=i,j,k,l< N)``` that has the following property

````T_{ijkl}```` is nonzero if ````i+j=k+l````

which acts as a "selection rule".

You want to contract the tensor T with another tensor u to make a third tensor v as follows

```v_{ij} = sum_{kl=0}^N T_{ijkl} u_{kl}```

is there a way to do this construction such that:

a. Is there anyway to pass this extra information to ```einsum/opt_einsum'''

b. Uses the explicit symmetry of the tensor, i.e the above operation should require $O(N^3)$ operations, not ```$O(N^4)$```.

One could use einsum directly getting $O(N^4)$ operations:
```
v = np.einsum('ijkl,ij->kl',T,u)
```
Or one could do a custom triple loop (using numba) as
```
v = np.zeros_like(u)
@jit(nopython=True)
def sym_summ(T,u,N,v):
    for i in range(N):
        for j in range(N):
            for k in range(max(1+i+j-N,0),min(i+j,N-1)+1):
                v[i,j]+=T[i,j,k,i+j-k]*u[k,i+j-k]

```
Note that for N=10 the numba code takes ~ 4 microsecond vs 40 microseconds using einsum.

Thanks!

**Comment by jcmgray** [comment]
Most of the machinery of ``opt_einsum`` is focussed on finding the 'contraction path' of einsum expressions with 2+ terms. It then dispatches to ``tensordot`` etc. to perform the pairwise contractions, often with ``numpy``, but potentially using any library with a matching API. 

Which is all to say that these kind of optimizations based on the structure of the tensors are left to the backend which provides the ``tensordot/einsum`` implementation (& can be specified with ``backend='mySelectionRuleLib'`` e.g.).

[sparse](https://github.com/pydata/sparse) is one such library which obviously already takes into account sparsity, but performance might not be as good as the custom code you have.

**Comment by nquesada** [comment]
On quick note: Seems like some tensor network packages allow for having selection rules in tensor contractions cf. https://itensor.org/docs.cgi?vers=cppv3&page=classes/qn

**Comment by jcmgray** [comment]
Yeah it would be *great* to have a python package for abelian tensors that handles the symmetries on an atomistic level, then ``opt_einsum`` could use it as the backend with absolutely no extra effort as long it used the ``tensordot``/``einsum`` API (the symmetry information would have to be carried around by the tensors).

The closest at the moment seems to be https://github.com/mhauru/tensors. But I haven't tested so don't know about performance and API. If the charge sectors (blocks) are small (such as in your first example where they are size 1), performance might be bad for a python implementation without using ``numba`` or ``cython`` etc.

**Comment by dgasmith** [comment]
It is a bit rough to do tiles (blocks/sectors) in Python as a "good" size is typically on the order of (100 x 100) matrices meaning that the Python overhead can be quite rough. Dask Array may be a good trial target for this as well since its automated tiling capability is pretty performant, but I am unsure how you would add symmetry to it.

It may eventually be possible to use C++ libraries like TiledArray/Cyclops in Python, but these libraries primarily target massively parallel and may have poor performance on a single node.

An automated way of handling this with Numba is quite appealing. As long as you can avoid sparsity /disk considerations, a jit way of handling this shouldn't be too bad, especially if you stick to GEMM and inner-product like cases.
