### ISSUE TITLE
Other backends: tensorflow, theano, sparse, dask etc

### ISSUE THREAD

**Issue by jcmgray** [dgasmith/opt_einsum#16]
What do you think about adding other (optional) backends?

I have this branch for gpu support [here](https://github.com/jcmgray/opt_einsum/tree/gpu-support) which was a fairly simple tweak to test using gpus with ``tensorflow``, ``theano`` and ``cupy``. It would also be very simple to add more backends since mostly they just need to implement ``tensordot`` and ``transpose`` (only ``einsum`` for non-blas operations).

Anyway here's a brief summary of the possible ndarray libraries:

| Library  | Tensordot? | Einsum? |
| ------------- | ------------- | ------ |
| [tensorflow](https://github.com/tensorflow/tensorflow) | yes | yes |
| [theano](https://github.com/Theano/Theano) | yes | no |
| [cupy](https://github.com/cupy/cupy) | yes | yes |
| [dask](https://github.com/dask/dask) | yes | [not yet?](https://github.com/dask/dask/issues/732) |
| [sparse](https://github.com/pydata/sparse) | yes | [not yet?](https://github.com/pydata/sparse/issues/31) |
| [tblis python](https://github.com/devinamatthews/tblis/tree/python) | would be easy to implement I think? | yes |

``tensorflow``, ``theano`` and I guess ``dask`` fit nicely with ``ContractExpression`` since they build/compile the graph of all the operations first.

**Comment by dgasmith** [comment]
Im a fan, its something that I was toying with before. I think we admitting defeat on the ability to do very low latency computations and instead focusing on moderate to large contractions where a small overhead is near-zero. Therefore, small additional logic layers are not a big deal.

As a note I was playing with adding a python-based TBLIS interface along with a few other folks. I think I actually promised I would do this, but have since become a bit busy. It would be very nice if this could be picked back up.

**Comment by jcmgray** [comment]
So, in addition to #17, I've made a small pull request to ``tblis`` which adds tensordot (https://github.com/devinamatthews/tblis/pull/17) and can confirm it works nicely as a backend.

**Comment by dgasmith** [comment]
Cool, great you are expanding on the TBLIS interface. We should really get in there and add tests and a setup.py at some point.
