### ISSUE TITLE
Customize library in binary contractions

### ISSUE THREAD

**Issue by Lancashire3000** [dgasmith/opt_einsum#177]
From https://dgasmith.github.io/opt_einsum/index.html
I can see `opt-einsum` loads a couple of libraries
```
--------------------------------------------------------------------------------
scaling   BLAS                  current                                remaining
--------------------------------------------------------------------------------
   5      GEMM            ijkl,pi->jklp                      qj,rk,sl,jklp->pqrs
   5      GEMM            jklp,qj->klpq                         rk,sl,klpq->pqrs
   5      GEMM            klpq,rk->lpqr                            sl,lpqr->pqrs
   5      GEMM            lpqr,sl->pqrs                               pqrs->pqrs
```
There is a `tblis` that seems to be an upgraded version of `GEMM`, https://github.com/devinamatthews/tblis/wiki/Tensor-Operations
and it has some python interface `https://pyscf.org/install.html#tblis` (for an installation experience, see https://github.com/pyscf/pyscf/issues/1108)

is that possible to load `tblis` into `opt-einsum` as the `GEMM`?

**Comment by jcmgray** [comment]
It is possible, but currently in a slightly hacky way. The first thing is to swap in the `einsum` implementation:

```python
from opt_einsum.backends.dispatch import _cached_funcs
_cached_funcs['einsum', 'numpy'] = the_new_einsum_fn
```
then when you do the contraction you want `use_blas=False`
```python
oe.contract(eq, *arrays, use_blas=False)
```
which would force the contraction engine use `einsum` for every pairwise operation rather than `tensordot` where possible.

---

Maybe we could think about adding it as an optional preset backend (i.e. ``oe.contract(..., backend='tblis')``) if the performance is good. (Although installation lightness wise e.g. looks like currently it requires the full `pyscf` as well?).

**Comment by dgasmith** [comment]
The author of that package is a friend and it is amazing for tensor contraction (especially skipping many in-memory copies!); however, the distribution around it isn't great. Until it has a native python interface of its own and is on conda-forge or a similar channel I don't think we should be writing bindings for it however.

I would be much more in favor of having an API so that users can extend the backend capabilities in their own code. We would want to be careful however and ensure that third party packages could not override native numpy/tensorflow/etc calls.

**Comment by Montagna2023** [comment]
> It is possible, but currently in a slightly hacky way. The first thing is to swap in the `einsum` implementation:
> 
> ```python
> from opt_einsum.backends.dispatch import _cached_funcs
> _cached_funcs['einsum', 'numpy'] = the_new_einsum_fn
> ```
> 
> then when you do the contraction you want `use_blas=False`
> 
> ```python
> oe.contract(eq, *arrays, use_blas=False)
> ```
> 
> which would force the contraction engine use `einsum` for every pairwise operation rather than `tensordot` where possible.
> 
> Maybe we could think about adding it as an optional preset backend (i.e. `oe.contract(..., backend='tblis')`) if the performance is good. (Although installation lightness wise e.g. looks like currently it requires the full `pyscf` as well?).

Thanks a lot. I will try and see if I can get any results in this approach (sorry for late response).

**Comment by Lancashire3000** [comment]
> It is possible, but currently in a slightly hacky way. The first thing is to swap in the `einsum` implementation:
> 
> ```python
> from opt_einsum.backends.dispatch import _cached_funcs
> _cached_funcs['einsum', 'numpy'] = the_new_einsum_fn
> ```
> 
> then when you do the contraction you want `use_blas=False`
> 
> ```python
> oe.contract(eq, *arrays, use_blas=False)
> ```
> 
> which would force the contraction engine use `einsum` for every pairwise operation rather than `tensordot` where possible.
> 
> Maybe we could think about adding it as an optional preset backend (i.e. `oe.contract(..., backend='tblis')`) if the performance is good. (Although installation lightness wise e.g. looks like currently it requires the full `pyscf` as well?).

Thank you so much! Actually from my preliminary experience, `_cached_funcs['einsum', 'numpy'] = tblis_einsum.contract` works fastest, especially there is some higher rank tensor (rank>=6); when added  `use_blas=False` the performance gets slower.
