### ISSUE TITLE
`einsum` alias

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#91]
Should we alias `contract` to `einsum` to allow a more drop-in replacement approach?

```
from opt_einsum import einsum

einsum(...)
```

As a note this would not remove the `contract` function, but simply alias it? We could also consider putting a deprecation warning around `contract` if we do feel like deprecating it. It could be desirable to be more "NEP18-like".

**Comment by fritzo** [comment]
Well users can already
```py
from opt_einsum import contract as einsum
```

**Comment by dgasmith** [comment]
@jcmgray want to weigh in here? We have a neutral comment and a thumbs up.

**Comment by jcmgray** [comment]
I feel fairly neutral as well. Personally I would be happy to have ``oe.einsum`` but it could be confusing for users who might suspect they have different functionality, and deprecating ``contract``, which is really the core function, I feel is a no-go. 

A compromise might just be to put the ``from opt_einsum import contract as einsum`` example more prominently in the docs.

**Comment by shoyer** [comment]
There are at least three ways `opt_einsum` could use protocols like NEP-18 (`__array_function__`):

1. It could leverage `__array_function__` overrides of core NumPy functions, so backend specific code doesn't necessarily need to live inside `opt_einsum`. `opt_einsum.contract` could auto-magically work on arrays of the appropriate type, even without the `backend` being set explicitly (I'm actually not sure why you have this already). To make this easy for users, you could list the explicit set of NumPy functions you expect, e.g., `tensordot` and `transpose`.
2. `opt_einsum` could define it's `contract` function as something that can be overriden by third-party libraries, like `einsum` itself is in NumPy. I don't think this version particularly makes sense, because opt-einsum is all about defining an efficient implementation for users.
3. `opt_einsum` could (theoretically) replace NumPy's own implementation of `np.einsum` on NumPy arrays. Such a "backend" system for swapping out the implementation of NumPy functions currently does not exist. But if the use cases for this are compelling enough, it's something we could consider. @peterbell10 is currently implementing something like this for `scipy.fft` as a Google Summer of Code project, and @hameerabbasi has been exploring APIs for doing this sort of thing in his [uarray](https://github.com/Quansight-Labs/uarray) project.

**Comment by dgasmith** [comment]
@shoyer Thank you for commenting.

We made `opt_einsum.contract` automagically work on arrays without setting the backend explicitly quite recently. I wasn't aware that `__array_function__` was in a state that we could rely on it. Do you have an example that we could pull from? Do we list `tensordot` and `transpose` in docs or is there a programatic way of performing this?

Everything else makes perfect sense. (3) is something that would be appropriate in the future, is there a pre-existing place for this conversation that we could jump into?

**Comment by shoyer** [comment]
> I wasn't aware that `__array_function__` was in a state that we could rely on it. Do you have an example that we could pull from? Do we list `tensordot` and `transpose` in docs or is there a programatic way of performing this?

`__array_function__` is enabled by default in the (most recent) NumPy 1.17 release, and dask, cupy and pydata/sparse already support.

Something the following should work for detecting if it's enabled or not:
```python
import os
import numpy as np
from distutils.version import LooseVersion

def array_function_enabled():
  numpy_version = LooseVersion(np.__version__)
  env_variable = os.environ.get('NUMPY_EXPERIMENTAL_ARRAY_FUNCTION')
  return (numpy_version >= '1.17' and env_variable != '0'
          or numpy_version >= '1.16' and env_variable == '1')
```

So your logic (for implementing 1) would look something like:
```python
def contract(...):
    if array_function_enabled() and any(
            hasattr(array, '__array_function__') for array in arrays):
        #  use np.transpose and np.tensordot directly
    else:
        # fall back to existing logic
```

> Everything else makes perfect sense. (3) is something that would be appropriate in the future, is there a pre-existing place for this conversation that we could jump into?

Either GitHub or the numpy-discussion mailing list would be appropriate places to bring this up. I haven't seen it discussed before.

**Comment by dgasmith** [comment]
Tied to #46. We could implement in the future; however, it doesn't appear to be the primary use case for the library.
